[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:flask]
command=python /app/api/backend.py
directory=/app/api
autostart=true
autorestart=true
stderr_logfile=/var/log/flask/error.log
stdout_logfile=/var/log/flask/access.log
environment=PYTHONUNBUFFERED="1"